<?php

namespace AppBundle\Repository;

/**
 * Data_appRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Data_appRepository extends \Doctrine\ORM\EntityRepository
{
}
