<?php

namespace AppBundle\Repository;

/**
 * Object_entryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Object_entryRepository extends \Doctrine\ORM\EntityRepository
{
}
