imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@FrontBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@AppBundle/Resources/config/services.yml" }


parameters:
    locale: fr
    upload_directory: '%kernel.project_dir%/web/uploads'
    cache_directory: '%kernel.project_dir%/web/cache'
    web_directory: '%kernel.project_dir%/web'

framework:
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        basepath: '%base_path%'
        numberusers: '%number_circle_users%'
    date:
          timezone: Europe/Paris

doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        form:
            type: AppBundle\Form\RegistrationType
    profile:
        form:
            type: AppBundle\Form\EditProfileType

liip_imagine :
    resolvers :
        default :
            web_path : ~

        photos:
          web_path:
            # use %kernel.project_dir%/web for Symfony prior to 4.0.0
            web_root: "%kernel.project_dir%/web"
            cache_prefix: "media/cache"

    filter_sets :
        cache : ~

        # profile_thumb
        profile_thumb_small:
            # adjust the image quality to 75%
            quality : 75
            # list of transformations to apply (the "filters")
            filters :

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail  : { size : [50, 50], mode : outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background : { size : [50, 50], position : center, color : '#ffffff' }

        profile_thumb_small_2x:
            quality : 100
            filters :
                thumbnail  : { size : [100, 100], mode : outbound }
                background : { size : [100, 100], position : center, color : '#ffffff' }

        profile_thumb_medium:
            quality : 75
            filters :
                thumbnail  : { size : [100, 100], mode : outbound }
                background : { size : [100, 100], position : center, color : '#ffffff' }

        profile_thumb_medium_2x:
            quality : 100
            filters :
                thumbnail  : { size : [200, 200], mode : outbound }
                background : { size : [200, 200], position : center, color : '#ffffff' }

        profile_thumb_big:
            quality : 75
            filters :
                thumbnail  : { size : [215, 215], mode : outbound }
                background : { size : [215, 215], position : center, color : '#ffffff' }

        profile_thumb_big_2x:
            quality : 100
            filters :
                thumbnail  : { size : [430, 430], mode : outbound }
                background : { size : [430, 430], position : center, color : '#ffffff' }

        # cloud_thumb
        cloud_thumb:
            cache: photos
            quality : 75
            filters :
                thumbnail  : { size : [215, 215], mode : outbound }
                background : { size : [215, 215], position : center, color : '#ffffff' }

        cloud_thumb_2x:
            cache: photos
            quality : 100
            filters :
                thumbnail  : { size : [430, 430], mode : outbound }
                background : { size : [430, 430], position : center, color : '#ffffff' }

        # cloud_modal
        cloud_modal_320w:
            cache: photos
            quality : 75
            filters :
                relative_resize:
                    widen : 320
                resample:
                    unit: ppi
                    x: 326
                    y: 326
                    filter: lanczos

        cloud_modal_640w:
            cache: photos
            quality : 75
            filters :
                relative_resize:
                    widen : 640
                resample:
                    unit: ppi
                    x: 264
                    y: 264
                    filter: lanczos

        cloud_modal_1024w:
            cache: photos
            quality : 75
            filters :
                relative_resize:
                    widen : 1024
                resample:
                    unit: ppi
                    x: 75
                    y: 75
                    filter: lanczos

        cloud_modal_1280w:
            cache: photos
            quality : 75
            filters :
                relative_resize:
                    widen : 1280
                resample:
                    unit: ppi
                    x: 75
                    y: 75
                    filter: lanczos

        # original
        original:
            cache: photos
            quality : 100
