app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ajaxSendMessage:
  path: /ajax/sendMessage
  defaults: { _controller: AppBundle\Controller\DefaultController::sendMessageAction }
  requirements:
    _method: POST|GET