# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form.registration:
            class: AppBundle\Form\RegistrationType
            tags:
                - { name: form.type, alias: app_user_registration }

    user.form.registration:
            class: UserBundle\Form\RegistrationFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: user_registration }

    user.file_uploader:
            class: AppBundle\Services\FileUploader
            arguments: ['%upload_directory%']

    user.doctrine_user_listener:
            class: AppBundle\EventListener\UserUploadListener
            arguments: ['@user.file_uploader']
            tags:
                - { name: doctrine.event_listener, event: prePersist }
                - { name: doctrine.event_listener, event: preUpdate }
                - { name: doctrine.event_listener, event: postLoad }
                - { name: doctrine.event_listener, event: preRemove }