# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #userBundleService:
    #    class: UserBundle\Services\UserBundleService
    #    arguments: ['@fos_user.user_manager']
